### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sebastiancretu** [ConnectHolland/cookie-consent-bundle#14]
Hi, and sorry for intruding.. I am trying to activate the bundle on an symfony4, but with no success. I followed the steps in the readme, set the config in services.yaml, activated the bundle (ConnectHolland\CookieConsentBundle\CHCookieConsentBundle::class => ['all' => true],) in bundles.php and after I insert the render in twig template, and i receive the following error:

`An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "ch_cookie_consent.show_if_cookie_consent_not_set" as such route does not exist.").`

Can you give me a starting point of how can i fix it ?

Thank you for your time, and this is a great bundle. I searched for one like this for a long time.

**Comment by matthijsch** [comment]
The routing should be loaded automatically when the symfony recipe PR I've created has been merged ( https://github.com/symfony/recipes-contrib/pull/614 ). Till then you will have to load the routing yourself by adding this in your routing config

```
ch_cookie_consent:
    resource: "@CHCookieConsentBundle/Resources/config/routing.yaml"
```

**Comment by sebastiancretu** [comment]
Thank you. It works now. Unfortunately jquery breaks the design. I will try to find a solution.
