### ISSUE TITLE
show one time more after agreat

### ISSUE THREAD

**Issue by xorgxx** [ConnectHolland/cookie-consent-bundle#18]
Hi thank for your bundle. i have set your bundle on SF4.2 all since to work well excepte that i have one probleme.
when i clic on button to agreat it das do the job but when it refresh the page it show again the cookie form. i suppose if you agreat one time it shud not show to ask again.
 for info : the first time you agreat in dump session all cookie are there.

thank for your help.

**Comment by xorgxx** [comment]
as i can see in your code it alway check in ```isCookieConsentSavedByUser()``` and ```return $this->show();``` before it save the cookie in ```save()``` maybe that the probleme come form here?

**Comment by matthijsch** [comment]
You're right. This won't be an issue when the form is submitted via ajax

**Comment by man-andy** [comment]
Thanks @matthijsch ! 🎉

**Comment by matthijsch** [comment]
Submitting forms via ajax has been implemented in the latest release (see #20). With this this issue won't occur
