### ISSUE TITLE
Parameter : template override

### ISSUE THREAD

**Issue by xorgxx** [ConnectHolland/cookie-consent-bundle#22]
HI and tank for ajax !!

i have big problem with css !! i need to override all ```cookie_consent.html.twig``` can it be possible to add in "config.yaml" parameter to choise template to render?

Thank

**Comment by matthijsch** [comment]
No that's not possible. You should just create a new template file in app/Resources/CHCookieConsentBundle/views/cookie_consent.html.twig. Then you can either 

- use defined blocks by extending the existing twig file by adding the following in your twig file
```
{% extends '@!CHCookieConsent/cookie_consent.html.twig' %}
```

- or create your own custom html with the data available in your twig file

**Comment by xorgxx** [comment]
you mean Template/CHCookieConsentBundle/views/cookie_consent.html.twig i'm on SF4.2

**Comment by matthijsch** [comment]
yes that's right

**Comment by xorgxx** [comment]
Sorry i did not all understand : my problem is that i have to change all structures of cookie_consent.html.twig and i can’t extend form '@!CHCookieConsent/cookie_consent.html.twig'. It's only to change "block" i need to change all to render as modale overlay.

**Comment by xorgxx** [comment]
So i find where was my problem : (SF4.2)

Template/CHCookieConsentBundle/views/cookie_consent.html.twig
TO
Template/bundles/CHCookieConsentBundle/cookie_consent.html.twig 
Thank's

**Comment by kamykm** [comment]
Just a note for people working with Symfony 5
One needs to create template file in:  templates/bundles/CHCookieConsentBundle

In addition, you may encounter a problem with "title" block name which is an example one in the docs.
The name title for a block is quite common. Therefore in my case was already defined. Unfortunately, in my case, I did not get simple error info but an infinite loop looking like this:

Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show". 
Jan  3 12:24:32 |INFO | REQUES Matched route "ch_cookie_consent.show".
