### ISSUE TITLE
Route not found and render issue on Symfony 3.4

### ISSUE THREAD

**Issue by Cafeba** [ConnectHolland/cookie-consent-bundle#25]
Hi,

I can't integrate this bundle into Symfony 3.4
There is 2 errors:

- Route not found
- Render doesn't work

**Comment by reyostallenberg** [comment]
I think PR https://github.com/ConnectHolland/cookie-consent-bundle/pull/30 will solve your problems

**Comment by reyostallenberg** [comment]
Fixed by #30
