### ISSUE TITLE
add remane cookie variable.

### ISSUE THREAD

**Issue by xorgxx** [ConnectHolland/cookie-consent-bundle#27]
Hi all work find for me, but i have one requeste : it is possible to add possibility to rename in config yml "name of the cookie" ex. "Cookie_Consent_Key, Cookie_Category_analytics ..."

thank

**Comment by reyostallenberg** [comment]
Hi @xorgxx, 

Thanks for your issue.
Can you provide a PR to accomplish your solution?

(With naming the categories other, you're half-way)

**Comment by xorgxx** [comment]
Hi it can be just modify "Cookie_Consent" and "Cookie_Category" by a variable in the config.yml
```
ch_cookie_consent:
    theme: 'dark' # light, dark
    categories: # Below are the default supported categories
        - 'analytics'
        - 'tracking'
        - 'marketing'
        - 'social_media'
    use_logger: false # Logs user actions to database
    prefix_cookie : 'noex' -> neox_consent; neox_category_analytics; ......
```
i think it's the faste and easy way?

regard

**Comment by reyostallenberg** [comment]
Can you provide a PR to accomplish your solution?

**Comment by xorgxx** [comment]
do you think it's he good solution?

**Comment by reyostallenberg** [comment]
Being able to prefix this cookie names is a good solution I think.

**Comment by xorgxx** [comment]
so i have done to add in config/packages/ch_cookie_consent.yaml : 
```
~~
    # add trying
    cookie_prefix: 'neo_Consent'                                          # 'cookie_Consent'
    cookie_key_name: 'neo_Consent_Key'                                    # 'cookie_Consent_Key'
    cookie_consent_name: 'neo_Category_'                                  # 'cookie_Category_'~
~~
```
since to work !! i have to make test before PR.

**Comment by reyostallenberg** [comment]
I do not understand your comment.

**Comment by xorgxx** [comment]
just finish my solution to modify "Cookie_Consent" and "Cookie_Category" by adding variable in the config.yml
~~
    # add trying
    cookie_prefix: 'neo_Consent'                                          # 'cookie_Consent'
    cookie_key_name: 'neo_Consent_Key'                                    # 'cookie_Consent_Key'
    cookie_consent_name: 'neo_Category_'                                  # 'cookie_Category_'~
~~
```
