### ISSUE TITLE
Unknown "chcookieconsent_isAllowed" function.

### ISSUE THREAD

**Issue by valgreg** [ConnectHolland/cookie-consent-bundle#36]
Hi all !

When i try 
`{% if chcookieconsent_isAllowed('analytics') == true %}
    ...
{% endif %}`

I've an error : Unknown "chcookieconsent_isAllowed" function.

Sf4 ver. 4.3.4
php: 7.3.9

**Comment by matthijsch** [comment]
We've changed the name of the twig function to "chcookieconsent_isCategoryAllowedByUser"

we will fix the README

**Comment by valgreg** [comment]
Thx guy ^^
