### ISSUE TITLE
Allow doctrine/doctrine-bundle 2.x?

### ISSUE THREAD

**Issue by crabnky** [ConnectHolland/cookie-consent-bundle#41]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for connectholland/cookie-consent-bundle ^0.8.0 -> satisfiable by connectholland/cookie-consent-bundle[0.8.0].
    - Conclusion: remove doctrine/doctrine-bundle 2.0.2
    - Conclusion: don't install doctrine/doctrine-bundle 2.0.2
    - connectholland/cookie-consent-bundle 0.8.0 requires doctrine/doctrine-bundle ^1.10 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.2].
    - Can only install one of: doctrine/doctrine-bundle[1.10.0, 2.0.2].
    - Can only install one of: doctrine/doctrine-bundle[1.10.1, 2.0.2].
    - Can only install one of: doctrine/doctrine-bundle[1.10.2, 2.0.2].
    - Can only install one of: doctrine/doctrine-bundle[1.10.3, 2.0.2].
    - Can only install one of: doctrine/doctrine-bundle[1.11.0, 2.0.2].
    - Can only install one of: doctrine/doctrine-bundle[1.11.1, 2.0.2].
    - Can only install one of: doctrine/doctrine-bundle[1.11.2, 2.0.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.0, 2.0.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.1, 2.0.2].
    - Can only install one of: doctrine/doctrine-bundle[1.12.2, 2.0.2].
    - Installation request for doctrine/doctrine-bundle (locked at 2.0.2) -> satisfiable by doctrine/doctrine-bundle[2.0.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by matthijsch** [comment]
Thanks for your issue. It will be fixed by #42

**Comment by crabnky** [comment]
Thanks much!!
