### ISSUE TITLE
Add support for Symfony v4.4

### ISSUE THREAD

**Issue by crabnky** [ConnectHolland/cookie-consent-bundle#43]
`Cannot autowire service "ConnectHolland\CookieConsentBundle\Cookie\CookieLogger": argument "$registry" of method "__construct()" references interface "Symfony\Bridge\Doctrine\RegistryInterface" but no such service exists. Try changing the type-hint to "Doctrine\Common\Persistence\ManagerRegistry" instead.`

See symfony/symfony#32394

**Comment by oliverfehmel** [comment]
Same problem here. Can be adjusted by changing use of RegistryInterface to ManagerRegistry shown in this upgrade file for doctrine: [https://github.com/doctrine/DoctrineBundle/blob/master/UPGRADE-2.0.md]

**Comment by matthijsch** [comment]
Thank you for submitting your issue. It should be fixed with #44

**Comment by matthijsch** [comment]
A new release has been created which should fix any issues with Symfony 4.4 and 5

**Comment by oliverfehmel** [comment]
Thanks for this quick support, but unfortenatly it wasn't successful for the CookieConsentController. This error message appears:

`Cannot autowire service "ConnectHolland\CookieConsentBundle\Controller\CookieConsentController": argument "$translator" of method "__construct()" references class "Symfony\Component\Translation\Translator" but no such service exists. Try changing the type-hint to one of its parents: interface "Symfony\Component\Translation\TranslatorInterface", or interface "Symfony\Contracts\Translation\TranslatorInterface".`

**Comment by crabnky** [comment]
Same here.

**Comment by oliverfehmel** [comment]
Can be solved be changing Translator usage in the Controller at line 19

`use Symfony\Component\Translation\Translator;`

should be

`use Symfony\Contracts\Translation\TranslatorInterface as Translator;`

**Comment by oliverfehmel** [comment]
PR is open [#45](https://github.com/ConnectHolland/cookie-consent-bundle/pull/45)

**Comment by kaamui** [comment]
Hello,

I think the last commit breaks compatibility with Symfony 3.4 : 

`composer require connectholland/cookie-consent-bundle`

![image](https://user-images.githubusercontent.com/11720903/70714132-cb2d7b00-1ce7-11ea-930e-9f7e90a9ccf8.png)

I tried to add this using composer before reinstalling ch-cookie-consent : 

"symfony/translation": "3.4.*"

but same issue as you can see in the image above...

Did I miss something with dependencies ?

**Comment by kaamui** [comment]
By using the 0.8.2 version, I end in a totally different error (without the last commit, so), but not sure what's the reason : 

![image](https://user-images.githubusercontent.com/11720903/70717182-1d719a80-1cee-11ea-8be1-3d530d60ce68.png)


Did you already encounter it ?

**Comment by epoplive** [comment]
> Hello,
> 
> I think the last commit breaks compatibility with Symfony 3.4 :
> 
> `composer require connectholland/cookie-consent-bundle`
> 
> ![image](https://user-images.githubusercontent.com/11720903/70714132-cb2d7b00-1ce7-11ea-930e-9f7e90a9ccf8.png)
> 
> I tried to add this using composer before reinstalling ch-cookie-consent :
> 
> "symfony/translation": "3.4.*"
> 
> but same issue as you can see in the image above...

I am also having this same issue... :(

**Comment by edezacas** [comment]
@kaamui @epoplive I've resolved this issue adding to services.yml the relation between TranslatorInterface and its service id:

```
Symfony\Contracts\Translation\TranslatorInterface: '@translator'
```

Now Symfony knows which service identifies TranslatorIntercace. 

I hope this will help you.
