### ISSUE TITLE
No ReponseEvent class found

### ISSUE THREAD

**Issue by mwillecke** [ConnectHolland/cookie-consent-bundle#47]
While on symfony 5 with bundle version 0.8.3 the following code throws "No ReponseEvent class found"

in ....\vendor\connectholland\cookie-consent-bundle\EventSubscriber\CookieConsentFormSubscriber.php (line 64)

/**
     * Checks if form has been submitted and saves users preferences in cookies by calling the CookieHandler.
     */
    public function onResponse(KernelEvent $event): void
    {
        if ($event instanceof FilterResponseEvent === false && $event instanceof ResponseEvent) {
            throw new \RuntimeException('No ReponseEvent class found');
        }

**Comment by matthijsch** [comment]
I've fixed a bug with the ResponseEvent, should work now

**Comment by mwillecke** [comment]
Yes, looks like.
Will check in more detail later. But first tests run successfull.
Many thanks for your fast solution.
