### ISSUE TITLE
Template override is not working

### ISSUE THREAD

**Issue by NiklasBr** [ConnectHolland/cookie-consent-bundle#57]
I'm following the readme which says I should place my override in `app/Resources/CHCookieConsentBundle/views/cookie_consent.html.twig`

I cannot for the life of me get that to work. I have also tried the following paths without luck:
- `app/Resources/views/cookie_consent.html.twig`
- `app/Resources/templates/cookie_consent.html.twig`
- `app/templates/cookie_consent.html.twig`

I'm using Symfony 4.4.7 with Twig 2.12.5

See below image for folder structure.

![cc-template-location](https://user-images.githubusercontent.com/279826/78867786-fc257e80-7a41-11ea-85a9-6d81a1bb0b65.PNG)

**Comment by matthijsch** [comment]
Can you try placing it in Templates/bundles/CHCookieConsentBundle/cookie_consent.html.twig

**Comment by NiklasBr** [comment]
Yes, `templates/bundles/CHCookieConsentBundle/cookie_consent.html.twig` works, thanks!

**Comment by crabnky** [comment]
There is wrong path specified in docs. See https://github.com/ConnectHolland/cookie-consent-bundle.
