### ISSUE TITLE
Shouldn't the form action be configurable?

### ISSUE THREAD

**Issue by gonzalovilaseca** [ConnectHolland/cookie-consent-bundle#59]
If a user goes to a specific page for the first time, the consent form will `POST` to that url, so in order to work all routes have to accept `POST`.
Wouldn't it be better to have a configurable path for the form action?
And have the save action point to a controller action instead of the listener building the form on every request?

**Comment by matthijsch** [comment]
That's indeed a valid issue I haven't thought of. I'll make these changes when I get the chance

**Comment by gonzalovilaseca** [comment]
I have cloned your repo and made the changes already, I jusst need to clean up and do a PR if that's ok.

**Comment by matthijsch** [comment]
That would be great, thanks!

**Comment by ttcremers** [comment]
Hi All, Any progress on the PR? Thanks

**Comment by danakil** [comment]
Hello, and thank you for your work !
Just had the same problem. I'd love an update on this issue :)

**Comment by plamenh** [comment]
Same here.

**Comment by matthijsch** [comment]
PR has been merged, thanks for the contribution!
