### ISSUE TITLE
Doctrine\Common is depreated

### ISSUE THREAD

**Issue by crabnky** [ConnectHolland/cookie-consent-bundle#68]
Hey, as far as I know, the Persistence directory of doctrine/common is now its own package and you should use its classes: the old ones are deprecated.

So in CookieLogger we should have `use Doctrine\Persistence\ManagerRegistry;` instead of `use Doctrine\Common\Persistence\ManagerRegistry;`

**Comment by crabnky** [comment]
Is this bundle abandoned? I can see the required changes in https://github.com/ConnectHolland/cookie-consent-bundle/pull/69... why is is not merged yet?

**Comment by matthijsch** [comment]
PR is merged. Bundle is not abandoned, only lacked time to focus on it
