### ISSUE TITLE
Set default checkbox value tu true

### ISSUE THREAD

**Issue by rogoit** [ConnectHolland/cookie-consent-bundle#76]
Hi and thx for your nice bundle. Will you still work on it?

Is there a way to set the checkboxes to true for the first user view? I do not think anyboday will check, just uncheck them.

See you
Roland

**Comment by NiklasBr** [comment]
https://gdpr.eu/gdpr-consent-requirements/ (with my emphasis)

> Consent of the data subject means any freely given, specific, informed and unambiguous indication of the data subject’s wishes by which he or she, *by a statement or by a clear affirmative action*, signifies agreement to the processing of personal data relating to him or her.
> [...]
> That is, there should be no question about whether the data subject has consented. *“Silence, pre-ticked boxes or inactivity should not therefore constitute consent,”* according to GDPR Recital 32.

It's pretty clear that we cannot check the boxes by default.

**Comment by rogoit** [comment]
Thx for your answer!!
