### ISSUE TITLE
Disable 'only functional cookies'

### ISSUE THREAD

**Issue by kamykm** [ConnectHolland/cookie-consent-bundle#88]
Hello,

Thank you for a nice bundle.
I am facing a problem with customization. The cookie consent is currently in simple mode. I would like to disable the possibility to click "only functional" cookies.  This way user will have only the possibility to accept all of the cookies or to walk through a not fully functional site. 

I can see:
`            $builder->add('use_only_functional_cookies', SubmitType::class, ['label' => 'ch_cookie_consent.use_only_functional_cookies', 'attr' => ['class' => 'btn ch-cookie-consent__btn']]);
`
in 
CookieConsentType->buildForm
but have no idea if I can easily  overwrite it somehow

**Comment by crabnky** [comment]
Just add this to your styles:
`button#cookie_consent_use_only_functional_cookies {
    display: none;
}`

**Comment by kamykm** [comment]
Thank you crabnky for your answer. I believe that CSS is not the solution here. One may simply use the browser console, remove this CSS property and submit the form.

**Comment by NiklasBr** [comment]
I don't fully understand you use case. Why are you concerned that someone will accept "only functional cookies" when that is pretty much a hard requirement by the GDPR?

**Comment by kamykm** [comment]
The case is quite simple. I want to simply disable part of the website if the visitor does not accept additional cookies. These cookies are essential for this site and the service may not be used otherwise. Therefore the user may:
- not to accept and have the cookie consent bar visible all the time and view part of the website (only button to accept all cookies visible)
- accept the additional cookies and see all the features (consent banner not visible any more)

**Comment by NiklasBr** [comment]
If they are truly essential for the service you do not need to ask for permission. You can simply not serve that functionality to them

**Comment by kamykm** [comment]
Yes. But imagine the following scenario:
1) User is entering the website. Cookie consent is visible.  Functionalities are limited.
2) User is clicking "only functional cookies"
3) Cookie consent disappears and cookies are set.
4) User is reading the content of the website and discovers that he wants to use this additional functionality and he would be willing to accept additional cookies
5) User has no easy way to do so  <- this is where the problem starts

I imagine 2 possible solutions:
Harder)  Making changes to the module that will enable the possibility for the user to change his mind. For this to happen the cookie consent would need to appear again and give the possibility to make a different choice.  
Easyer)  Make the cookie consent visible all the time until the user will notice that he needs to accept it to use the service. For this to happen I need to hide the "only functional" button for good.

**Comment by oliverfehmel** [comment]
But couldn't you build the first solution with a short js snippet? (removing cookie, reload page or rerender twig snippet)

**Comment by kamykm** [comment]
Thank you oliverfehmel for this idea. I like it for two reasons:
1) it is fairly simple
2) it is totally independent from cookie consent 
Don't really know why I didn't see this option in the first place. Possibly problem decomposition provided by this discussion was needed.

This approach is slightly less convenient for end-user (more clicks, more reading etc.) but still seems to be good enough.

**Comment by oliverfehmel** [comment]
It does not have to be inconvenient for end-users. Just do an ajax request and render the cookie-consent. So you do not have a page reload. If you want to reduce the amount of clicks as well you can set the functionality to the first button
