### ISSUE TITLE
Compatibility with php 8

### ISSUE THREAD

**Issue by Nenuial** [ConnectHolland/cookie-consent-bundle#92]
Are there any plans for php 8 compatibility?

**Comment by NiklasBr** [comment]
See pull #90

**Comment by AxelSOULARD** [comment]
When will the release be please ?

**Comment by Nenuial** [comment]
Any chance of seeing this PR merged in the coming weeks? This issue is preventing me from updating my project and I'd like to know if I should consider abandoning this CookieConsent bundle.

Don't get me wrong. I really appreciate the excellent work that was done here and I understand that there is no garantie what so ever with open source software. I just wish to know if the move towards PHP 8 compatibility is going to happen or if it is uncertain.

**Comment by NiklasBr** [comment]
@matthijsch maybe can check in?

**Comment by matthijsch** [comment]
Pr has been merged and a new release has been created. Thanks for contributing! Apologies for the delay

**Comment by Nenuial** [comment]
Thank you very much for the merge and release!
