### ISSUE TITLE
No route found for "POST /de_DE/": Method Not Allowed (Allow: GET)

### ISSUE THREAD

**Issue by TELLO0815** [ConnectHolland/cookie-consent-bundle#93]
I get AJAX error `No route found for "POST /de_DE/": Method Not Allowed (Allow: GET)` when save the form. (Symfony 4.4.21) 
Any idea?

**Comment by TELLO0815** [comment]
I have to enable POST for the route ;-)

**Comment by simonhard** [comment]
I created a pull request regarding that topic
https://github.com/ConnectHolland/cookie-consent-bundle/pull/106/files

**Comment by matthijsch** [comment]
PR has been merged, thanks for the contribution!
